"""graph_v9.py — L2 graph-connectivity features for shop joker valuation.

A heterogeneous "run graph" over the game state: joker / hand-type / deck-group
/ boss nodes with affinity edges auto-derived from the effect strings in
`tools/joker_spec.json` (the doc-pinned source of truth, generated by
tools/gen_joker_spec.py) — plus deck-support, hand-feasibility, and
boss-counter edges.

  joker_affinity(key)          — spec-derived affinity sets per joker (cached).
  deck_groups(game)            — full-deck composition (deck + hand + spent).
  build_run_graph(game, extra) — the heterogeneous graph structure (also the
                                 substrate for the planned L2 GAT).
  connectivity_features(...)   — [0,1] features for a candidate joker:
                                 coherence / deck_support / hand_alignment /
                                 boss_counter.
  connectivity_score(...)      — blended [0,1] score consumed by
                                 agent_v9.joker_value's graph term.

Everything here READS game state only — zero RNG consumption, zero mutation —
so it is safe inside the seed-exact sim and the isolated eval oracle.
"""
from __future__ import annotations

import os
import re
import warnings
from collections import Counter, defaultdict
from pathlib import Path
from typing import Optional

from .game import State, MATADOR_BOSSES

# ════════════════════════════════════════════════════════════════════════════
# Node vocabulary
# ════════════════════════════════════════════════════════════════════════════

HAND_TYPES = [
    "High Card", "Pair", "Two Pair", "Three of a Kind", "Straight", "Flush",
    "Full House", "Four of a Kind", "Straight Flush", "Five of a Kind",
    "Flush House", "Flush Five",
]

_SUITS = ["Spades", "Hearts", "Clubs", "Diamonds"]
_ENHANCEMENTS = ["Bonus", "Mult", "Glass", "Steel", "Stone", "Gold", "Lucky",
                 "Wild"]

# ════════════════════════════════════════════════════════════════════════════
# Spec loading (tools/joker_spec.json) — lazy, cached
# ════════════════════════════════════════════════════════════════════════════

_SPEC: Optional[dict] = None
_SPEC_WARNED = False


def _resolve_spec_path() -> Optional[Path]:
    """Find tools/joker_spec.json: env override, then the repo-root tools dir
    (graph_v9 lives at vendor/balatro-rl/balatro_sim/graph_v9.py → parents[3]
    is the repo root)."""
    env = os.environ.get("BALATRO_JOKER_SPEC")
    if env:
        p = Path(env)
        if p.exists():
            return p
    cand = Path(__file__).resolve().parents[3] / "tools" / "joker_spec.json"
    return cand if cand.exists() else None


def load_spec() -> dict:
    """The canonical joker spec (key -> cost/effect/name/timing/type)."""
    global _SPEC, _SPEC_WARNED
    if _SPEC is None:
        path = _resolve_spec_path()
        if path is None:
            if not _SPEC_WARNED:
                _SPEC_WARNED = True
                warnings.warn("graph_v9: tools/joker_spec.json not found — "
                              "affinities will be empty (connectivity ~ neutral)")
            _SPEC = {}
        else:
            import json
            _SPEC = json.loads(path.read_text(encoding="utf-8"))
    return _SPEC


# ════════════════════════════════════════════════════════════════════════════
# Keyword → affinity extraction from effect strings
# ════════════════════════════════════════════════════════════════════════════

_SUIT_WORDS = {
    "spade": "Spades", "spades": "Spades",
    "heart": "Hearts", "hearts": "Hearts",
    "club": "Clubs", "clubs": "Clubs",
    "diamond": "Diamonds", "diamonds": "Diamonds",
}
_RANK_WORDS = {
    "ace": 14, "aces": 14, "king": 13, "kings": 13, "queen": 12,
    "queens": 12, "jack": 11, "jacks": 11,
}
_RANK_WORDS.update({f"{r}": r for r in range(2, 11)})  # "2".."10"
# Words that mark an ENHANCEMENT affinity ("enhanced cards" is a generic flag).
_ENH_WORDS = {
    "glass": "Glass", "steel": "Steel", "stone": "Stone", "gold": "Gold",
    "lucky": "Lucky", "wild": "Wild", "bonus": "Bonus",
}

# Effect keywords -> behaviour flags (used for joker↔joker coherence edges and
# the boss-counter feature). Kept broad on purpose: shared mechanics cluster
# genuinely synergistic jokers (Baron+Mime via "held").
_FLAG_WORDS = {
    "held": "held",
    "boss": "boss",
    "money": "money", "dollars": "money", "interest": "money", "$": "money",
    "planet": "planet", "tarot": "tarot", "spectral": "spectral",
    "discard": "discard", "hand size": "hand_size",
    "retrigger": "retrigger", "deck": "deck", "enhanced": "enhanced",
    "face": "face",
}

_re_digit_word = re.compile(r"\b([2-9]|10)s?\b")
# Stat tokens that must NOT become rank affinities: "+10 Mult", "X2 Mult",
# "$4", "-2 hand size", "1 in 4 chance", "1 in 2".
_re_stat = re.compile(r"[+\-$x]\s*\d+(?:\.\d+)?")
_re_odds = re.compile(r"\b1 in \d+\s*(?:chance)?")


def _extract_affinity(effect: str) -> dict:
    """Parse one effect string into affinity sets (canonical casing: "Pair",
    "Spades", "King"). Stat/odds values ("+10 Mult", "X2", "1 in 4 chance")
    are stripped FIRST, and all keyword checks use word boundaries, so values
    and "Ace," style punctuation never leak in."""
    raw = effect.lower()
    clean = _re_odds.sub(" ", _re_stat.sub(" ", raw))
    text = f" {clean} "

    def has(word: str) -> bool:
        return re.search(rf"(?<![a-z0-9]){re.escape(word)}(?![a-z0-9])",
                         text) is not None

    hands = {h for h in HAND_TYPES if has(h.lower())}
    suits = {s for w, s in _SUIT_WORDS.items() if has(w)}
    ranks = {r for w, r in _RANK_WORDS.items() if has(w)}
    for m in _re_digit_word.finditer(clean):
        ranks.add(int(m.group(1)))
    enhs = {e for w, e in _ENH_WORDS.items() if has(w)}
    flags = {f for w, f in _FLAG_WORDS.items() if has(w)}
    if "$" in raw:
        flags.add("money")   # "$4" is stripped by _re_stat; keep the flag
    return {
        "hands": frozenset(hands), "suits": frozenset(suits),
        "ranks": frozenset(ranks), "enhs": frozenset(enhs),
        "flags": frozenset(flags),
    }


#: (key -> affinity dict), built lazily from the spec on first use.
_AFFINITY_CACHE: dict[str, dict] = {}


def joker_affinity(key: str) -> dict:
    """Spec-derived affinity sets for a joker key (cached; empty for unknown
    keys — connectivity treats them as neutral)."""
    aff = _AFFINITY_CACHE.get(key)
    if aff is None:
        spec = load_spec()
        entry = spec.get(key)
        aff = _extract_affinity(entry["effect"]) if entry else {
            "hands": frozenset(), "suits": frozenset(), "ranks": frozenset(),
            "enhs": frozenset(), "flags": frozenset(),
        }
        _AFFINITY_CACHE[key] = aff
    return aff


def affinity_items(aff: dict) -> set:
    """The flat affinity item set used for joker↔joker overlap (hand types,
    suits, ranks, enhancements, and behaviour flags)."""
    return set(aff["hands"]) | set(aff["suits"]) | set(aff["ranks"]) \
        | set(aff["enhs"]) | set(aff["flags"])


# ════════════════════════════════════════════════════════════════════════════
# Deck composition + boss context
# ════════════════════════════════════════════════════════════════════════════

def deck_groups(game) -> dict:
    """Full-deck composition counters — deck + hand + spent (what the deck
    will contain from the next blind on; mirrors the scoring engine's
    full-deck view)."""
    cards = list(game.deck) + list(game.hand) + list(getattr(game, "spent", ()))
    suits, ranks, enhs, seals, editions = (Counter(), Counter(), Counter(),
                                           Counter(), Counter())
    for c in cards:
        suits[c.suit] += 1
        ranks[c.rank] += 1
        if c.enhancement != "None":
            enhs[c.enhancement] += 1
        if getattr(c, "seal", "None") != "None":
            seals[c.seal] += 1
        if getattr(c, "edition", "None") != "None":
            editions[c.edition] += 1
    return {"suits": suits, "ranks": ranks, "enhs": enhs,
            "seals": seals, "editions": editions, "n": len(cards)}


def boss_context(game) -> tuple[bool, str]:
    """(boss_coming, boss_key_if_known) for the NEXT blind.

    During a shop (SHOP/BOOSTER_OPEN) the current_blind is the blind JUST
    fought; the next blind is a Boss iff we just fought the Big blind
    (blind_idx == 1). Since the boss-layer pass, the upcoming boss's KEY is
    pre-selected at shop entry (game.next_boss_key), so it is known while
    shopping — the boss-counter term can be key-specific (e.g. Matador only
    against its 13 trigger blinds). During/after selection (BLIND_SELECT
    onward) the boss key is current_blind.boss_key.
    """
    st = game.state
    if st in (State.SHOP, State.BOOSTER_OPEN):
        return (game.blind_idx == 1, getattr(game, "next_boss_key", "") or "")
    if st in (State.BLIND_SELECT, State.SELECTING_HAND, State.ROUND_EVAL,
              State.GAME_OVER):
        return (bool(getattr(game.current_blind, "is_boss", False)),
                getattr(game.current_blind, "boss_key", "") or "")
    return (False, "")


# ════════════════════════════════════════════════════════════════════════════
# The heterogeneous run graph
# ════════════════════════════════════════════════════════════════════════════

class RunGraph:
    """A heterogeneous graph over one game state.

    Node ids: "j:<key>" (joker), "h:<hand type>" (hand), "d:suit:<S>",
    "d:rank:<R>", "d:enh:<E>" (deck groups), "boss". Edges carry a kind:
    affinity (joker→hand/joker), support (joker→deck, weight = count/total),
    feasibility (hand→deck), counter (joker→boss)."""

    __slots__ = ("nodes", "edges", "_adj")

    def __init__(self):
        self.nodes: dict[str, dict] = {}      # id -> {"type", "key"}
        self.edges: list[tuple[str, str, float, str]] = []  # (src, dst, w, kind)
        self._adj: dict[str, list[tuple[str, float, str]]] = defaultdict(list)

    def add_node(self, nid: str, ntype: str, key: str) -> None:
        if nid not in self.nodes:
            self.nodes[nid] = {"type": ntype, "key": key}

    def add_edge(self, src: str, dst: str, weight: float, kind: str) -> None:
        self.edges.append((src, dst, weight, kind))
        self._adj[src].append((dst, weight, kind))
        self._adj[dst].append((src, weight, kind))

    def neighbors(self, nid: str) -> list[tuple[str, float, str]]:
        return self._adj.get(nid, [])


def build_run_graph(game, extra_jokers: tuple[str, ...] = ()) -> RunGraph:
    """Build the run graph: owned jokers (+ `extra_jokers` candidates) linked
    by affinity to hand-type / deck-group / boss nodes and to each other."""
    g = RunGraph()
    dg = deck_groups(game)
    total = max(1, dg["n"])
    boss_coming, boss_key = boss_context(game)

    # Hand-type nodes with deck-feasibility edges (the MOST-COMMON rank/suit
    # VALUE, not the max count — "d:rank:<rank>" node ids must be real ranks).
    top_rank = max(dg["ranks"], key=dg["ranks"].get) if dg["ranks"] else None
    top_suit = max(dg["suits"], key=dg["suits"].get) if dg["suits"] else None
    for ht in HAND_TYPES:
        hid = f"h:{ht}"
        g.add_node(hid, "hand", ht)
        if top_rank is not None and ht in (
                "Pair", "Two Pair", "Three of a Kind", "Four of a Kind",
                "Five of a Kind", "Full House", "Flush House", "Flush Five"):
            g.add_edge(hid, f"d:rank:{top_rank}",
                       dg["ranks"][top_rank] / total, "feasibility")
        if top_suit is not None and ht in (
                "Flush", "Straight Flush", "Flush House", "Flush Five"):
            g.add_edge(hid, f"d:suit:{top_suit}",
                       dg["suits"][top_suit] / total, "feasibility")

    # Deck-group nodes (only non-empty groups).
    for suit, cnt in dg["suits"].items():
        g.add_node(f"d:suit:{suit}", "deck", suit)
        g.add_edge(f"d:suit:{suit}", "h:Flush", cnt / total, "feasibility")
    for rank, cnt in dg["ranks"].items():
        g.add_node(f"d:rank:{rank}", "deck", rank)
        g.add_edge(f"d:rank:{rank}", "h:Pair", cnt / total, "feasibility")
    for enh, cnt in dg["enhs"].items():
        g.add_node(f"d:enh:{enh}", "deck", enh)
    if dg["n"]:
        g.add_node("d:size", "deck", "size")

    # Boss node.
    if boss_coming:
        g.add_node("boss", "boss", boss_key or "?")

    # Joker nodes + their edges.
    owned = [j.key for j in game.jokers]
    keys = list(dict.fromkeys(owned + list(extra_jokers)))  # dedupe, keep order
    for key in keys:
        nid = f"j:{key}"
        g.add_node(nid, "joker", key)
        aff = joker_affinity(key)
        for h in aff["hands"]:
            g.add_edge(nid, f"h:{h}", 1.0, "affinity")
        for s in aff["suits"]:
            sid = f"d:suit:{s}"
            g.add_node(sid, "deck", s)
            g.add_edge(nid, sid, dg["suits"].get(s, 0) / total, "support")
        for r in aff["ranks"]:
            rid = f"d:rank:{r}"
            g.add_node(rid, "deck", r)
            g.add_edge(nid, rid, dg["ranks"].get(r, 0) / total, "support")
        for e in aff["enhs"]:
            eid = f"d:enh:{e}"
            g.add_node(eid, "deck", e)
            g.add_edge(nid, eid, dg["enhs"].get(e, 0) / total, "support")
        if boss_coming and "boss" in aff["flags"]:
            g.add_edge(nid, "boss", 1.0, "counter")

    # Joker↔joker shared-affinity edges (only among owned + extra jokers).
    for i in range(len(keys)):
        for j in range(i + 1, len(keys)):
            a, b = joker_affinity(keys[i]), joker_affinity(keys[j])
            shared = affinity_items(a) & affinity_items(b)
            if shared:
                denom = max(1, min(len(affinity_items(a)), len(affinity_items(b))))
                g.add_edge(f"j:{keys[i]}", f"j:{keys[j]}",
                           len(shared) / denom, "affinity")
    return g


# ════════════════════════════════════════════════════════════════════════════
# Connectivity features + blended score (the shop-value term)
# ════════════════════════════════════════════════════════════════════════════

#: Feature blend weights for connectivity_score (all features in [0, 1]).
#: boss_counter is deliberately NOT in the blend — it gets its own dedicated
#: term (see boss_counter_value) so buying a Boss-counter joker is decided on
#: its own merits rather than diluted into the coherence blend.
FEATURE_WEIGHTS = {"coherence": 0.40, "deck_support": 0.30,
                   "hand_alignment": 0.30}

#: Boss-interaction jokers get the counter bonus from their spec "Boss" flag;
#: this set documents the expectation for tests (spec-derived, not consulted
#: by the code itself). Since the boss-layer pass, j_matador is KEY-conditional
#: (boss_counter_value only fires it against the 13 real trigger blinds —
#: MATADOR_BOSSES in game.py); j_chicot/j_luchador disable ANY boss, so they
#: fire whenever a Boss is next. j_mr_bones is deliberately absent: its spec
#: text ("Prevents Death if chips scored are at least 25%...") has no "Boss"
#: word, so it never carries the flag — it is a general death-save, not a
#: boss counter (its value shows up in marginal score instead).
BOSS_INTERACTION_JOKERS = frozenset({"j_chicot", "j_luchador", "j_matador"})


def connectivity_features(game, key: str) -> dict:
    """[0,1] connectivity features for candidate joker `key` in `game`:
      coherence      — mean shared-affinity edge weight vs owned jokers
                       (0.5 neutral when nothing is owned)
      deck_support   — best normalized deck-group count for the joker's
                       suit/rank/enhancement affinities (0.5 neutral when the
                       joker has no deck affinities)
      hand_alignment — 1.0 when the joker fires on the run's main hand type,
                       0.7 on any other played hand, 0.3 on an unplayed hand,
                       0.5 neutral (no hand affinity)
      boss_counter   — 1.0 when a Boss is the next blind and the joker's
                       effect interacts with Boss Blinds, else 0.0
    All reads — no RNG, no mutation."""
    aff = joker_affinity(key)
    owned = [j.key for j in game.jokers]

    # coherence
    cand_items = affinity_items(aff)
    if not owned:
        coherence = 0.5
    elif not cand_items:
        coherence = 0.0
    else:
        overlaps = []
        for okey in owned:
            o_items = affinity_items(joker_affinity(okey))
            shared = cand_items & o_items
            if shared:
                denom = max(1, min(len(cand_items), len(o_items)))
                overlaps.append(len(shared) / denom)
        coherence = (sum(overlaps) / len(owned)) if overlaps else 0.0

    # deck_support
    dg = deck_groups(game)
    total = max(1, dg["n"])
    support = 0.0
    if aff["suits"]:
        support = max(support, max(dg["suits"].get(s, 0) for s in aff["suits"]) / total)
    if aff["ranks"]:
        support = max(support, max(dg["ranks"].get(r, 0) for r in aff["ranks"]) / total)
    if aff["enhs"]:
        support = max(support, max(dg["enhs"].get(e, 0) for e in aff["enhs"]) / total)
    deck_support = support if (aff["suits"] or aff["ranks"] or aff["enhs"]) else 0.5

    # hand_alignment
    main = main_hand(game)
    if not aff["hands"]:
        hand_alignment = 0.5
    elif main in aff["hands"]:
        hand_alignment = 1.0
    elif any(c > 0 for h, c in game.run_hand_counts.items() if h in aff["hands"]):
        hand_alignment = 0.7
    else:
        hand_alignment = 0.3

    return {"coherence": coherence, "deck_support": deck_support,
            "hand_alignment": hand_alignment}


def main_hand(game) -> str:
    """The run's most-played hand type (tie-break by planet level)."""
    counts = game.run_hand_counts
    best, best_key = "High Card", (-1, -1)
    for ht, c in counts.items():
        key = (c, game.planet_levels.get(ht, 1))
        if key > best_key:
            best_key, best = key, ht
    return best


def connectivity_score(game, key: str) -> float:
    """Blended [0,1] graph-connectivity score for candidate joker `key`."""
    feats = connectivity_features(game, key)
    return sum(FEATURE_WEIGHTS[k] * feats[k] for k in FEATURE_WEIGHTS)


def boss_counter_value(game, key: str) -> float:
    """1.0 when a Boss is the next blind and `key` interacts with Boss Blinds
    (Chicot/Luchador/Matador — from the spec's "Boss" flag), else 0.0. Kept
    OUT of the blend: marginal score eval values these at ~0 (they add no
    chips/mult), so they need their own buy term (agent_v9's boss_buy_bonus)
    or they would never be purchased.

    Key-specific since the boss-layer pass: the upcoming boss's key is
    pre-selected at shop entry, so Matador only gets the bonus against one of
    its 13 real trigger blinds (MATADOR_BOSSES) — before a non-trigger boss
    (e.g. The Wall) its marginal value really is ~0 and it is skipped.
    Chicot/Luchador disable ANY boss, so they keep the bonus whenever a Boss
    is next. Unknown key (hand-constructed states that skipped the shop)
    falls back to the old any-boss behavior — conservative, keeps the bonus."""
    if "boss" not in joker_affinity(key)["flags"]:
        return 0.0
    boss_coming, boss_key = boss_context(game)
    if not boss_coming:
        return 0.0
    if boss_key and boss_key != "?" and key == "j_matador":
        return 1.0 if boss_key in MATADOR_BOSSES else 0.0
    return 1.0
