"""
shop.py — Shop generation, pricing, buy/sell logic.

The real Balatro shop (G.GAME.shop.joker_max) sells:
  - 2 random slots, each cdt-polled (Joker 71.4% / Tarot 14.3% / Planet
    14.3%) — Overstock / Overstock Plus add 1 slot each (3 / 4)
  - 1 Voucher slot
  - 2 Booster pack slots

Prices:
  Jokers: per-joker base cost (real game table — e.g. Joker $2, Blueprint $10,
          Legendary $20) + edition markup; see JOKER_CATALOGUE.
  Planet / Tarot:  $3
  Booster (std):   $4
  Voucher:         $10
  Playing card (Magic Trick): $1

Selling jokers: ~50% of buy price (rounded down), minimum $1.
"""
from __future__ import annotations
import random
from dataclasses import dataclass, field
from typing import Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from .game import BalatroGame

from .consumables import (
    ALL_PLANETS, ALL_TAROTS, ALL_SPECTRALS, ALL_VOUCHERS,
    PLANET_NAME, TAROT_NAME, VOUCHER_NAME, VOUCHER_BASE,
    PLANET_HAND,
)
from .seed_rng import (
    node_joker, node_rarity, node_edition, node_tarot, node_planet,
    node_spectral, node_voucher, node_shop_pack, node_stdset,
    node_std_enhanced, node_std_front, node_std_edition, node_std_seal,
    node_std_seal_type, node_cdt, MAGIC_CARD_NODE, OMEN_NODE, ILLUSION_NODE,
)
from .constants import ENHANCEMENTS

# Hand-tier order for Telescope's "higher tier hand" tie-break.
_HAND_TIERS = {h: i for i, h in enumerate([
    "High Card", "Pair", "Two Pair", "Three of a Kind", "Straight", "Flush",
    "Full House", "Four of a Kind", "Straight Flush", "Five of a Kind",
    "Flush House", "Flush Five",
])}

# ════════════════════════════════════════════════════════════════════════════
# JOKER CATALOGUE — all joker keys with rarity and base price
# ════════════════════════════════════════════════════════════════════════════

# ════════════════════════════════════════════════════════════════════════════
# JOKER CATALOGUE — canonical real-game ids, rarities, and base costs
# (rebuilt from balatro-rs joker_data!, the authoritative game table; costs
# wiki-verified). Effects resolve via JOKER_REGISTRY, incl. the canonical-key
# aliases registered in jokers/__init__.py.
# ════════════════════════════════════════════════════════════════════════════

# Generated by tools/gen_joker_catalogue.py from balatro-rs joker_data!
# Canonical real-game ids, real rarities, real base costs (wiki-verified).
JOKER_CATALOGUE: dict[str, dict] = {
    "j_joker": {"key": "j_joker", "name": "Joker", "rarity": "Common", "price": 2},
    "j_greedy_joker": {"key": "j_greedy_joker", "name": "Greedy Joker", "rarity": "Common", "price": 5},
    "j_lusty_joker": {"key": "j_lusty_joker", "name": "Lusty Joker", "rarity": "Common", "price": 5},
    "j_wrathful_joker": {"key": "j_wrathful_joker", "name": "Wrathful Joker", "rarity": "Common", "price": 5},
    "j_gluttenous_joker": {"key": "j_gluttenous_joker", "name": "Gluttonous Joker", "rarity": "Common", "price": 5},
    "j_jolly": {"key": "j_jolly", "name": "Jolly Joker", "rarity": "Common", "price": 3},
    "j_zany": {"key": "j_zany", "name": "Zany Joker", "rarity": "Common", "price": 4},
    "j_mad": {"key": "j_mad", "name": "Mad Joker", "rarity": "Common", "price": 4},
    "j_crazy": {"key": "j_crazy", "name": "Crazy Joker", "rarity": "Common", "price": 4},
    "j_droll": {"key": "j_droll", "name": "Droll Joker", "rarity": "Common", "price": 4},
    "j_sly": {"key": "j_sly", "name": "Sly Joker", "rarity": "Common", "price": 3},
    "j_wily": {"key": "j_wily", "name": "Wily Joker", "rarity": "Common", "price": 4},
    "j_clever": {"key": "j_clever", "name": "Clever Joker", "rarity": "Common", "price": 4},
    "j_devious": {"key": "j_devious", "name": "Devious Joker", "rarity": "Common", "price": 4},
    "j_crafty": {"key": "j_crafty", "name": "Crafty Joker", "rarity": "Common", "price": 4},
    "j_half": {"key": "j_half", "name": "Half Joker", "rarity": "Common", "price": 5},
    "j_stencil": {"key": "j_stencil", "name": "Joker Stencil", "rarity": "Uncommon", "price": 8},
    "j_four_fingers": {"key": "j_four_fingers", "name": "Four Fingers", "rarity": "Uncommon", "price": 7},
    "j_mime": {"key": "j_mime", "name": "Mime", "rarity": "Uncommon", "price": 5},
    "j_credit_card": {"key": "j_credit_card", "name": "Credit Card", "rarity": "Common", "price": 1},
    "j_ceremonial": {"key": "j_ceremonial", "name": "Ceremonial Dagger", "rarity": "Uncommon", "price": 6},
    "j_banner": {"key": "j_banner", "name": "Banner", "rarity": "Common", "price": 5},
    "j_mystic_summit": {"key": "j_mystic_summit", "name": "Mystic Summit", "rarity": "Common", "price": 5},
    "j_marble": {"key": "j_marble", "name": "Marble Joker", "rarity": "Uncommon", "price": 6},
    "j_loyalty_card": {"key": "j_loyalty_card", "name": "Loyalty Card", "rarity": "Uncommon", "price": 5},
    "j_8_ball": {"key": "j_8_ball", "name": "8 Ball", "rarity": "Common", "price": 5},
    "j_misprint": {"key": "j_misprint", "name": "Misprint", "rarity": "Common", "price": 4},
    "j_dusk": {"key": "j_dusk", "name": "Dusk", "rarity": "Uncommon", "price": 5},
    "j_raised_fist": {"key": "j_raised_fist", "name": "Raised Fist", "rarity": "Common", "price": 5},
    "j_chaos": {"key": "j_chaos", "name": "Chaos the Clown", "rarity": "Common", "price": 4},
    "j_fibonacci": {"key": "j_fibonacci", "name": "Fibonacci", "rarity": "Uncommon", "price": 8},
    "j_steel_joker": {"key": "j_steel_joker", "name": "Steel Joker", "rarity": "Uncommon", "price": 7},
    "j_scary_face": {"key": "j_scary_face", "name": "Scary Face", "rarity": "Common", "price": 4},
    "j_abstract": {"key": "j_abstract", "name": "Abstract Joker", "rarity": "Common", "price": 4},
    "j_delayed_grat": {"key": "j_delayed_grat", "name": "Delayed Gratification", "rarity": "Common", "price": 4},
    "j_hack": {"key": "j_hack", "name": "Hack", "rarity": "Uncommon", "price": 6},
    "j_pareidolia": {"key": "j_pareidolia", "name": "Pareidolia", "rarity": "Uncommon", "price": 5},
    "j_gros_michel": {"key": "j_gros_michel", "name": "Gros Michel", "rarity": "Common", "price": 5},
    "j_even_steven": {"key": "j_even_steven", "name": "Even Steven", "rarity": "Common", "price": 4},
    "j_odd_todd": {"key": "j_odd_todd", "name": "Odd Todd", "rarity": "Common", "price": 4},
    "j_scholar": {"key": "j_scholar", "name": "Scholar", "rarity": "Common", "price": 4},
    "j_business": {"key": "j_business", "name": "Business Card", "rarity": "Common", "price": 4},
    "j_supernova": {"key": "j_supernova", "name": "Supernova", "rarity": "Common", "price": 5},
    "j_ride_the_bus": {"key": "j_ride_the_bus", "name": "Ride the Bus", "rarity": "Common", "price": 6},
    "j_space": {"key": "j_space", "name": "Space Joker", "rarity": "Uncommon", "price": 5},
    "j_egg": {"key": "j_egg", "name": "Egg", "rarity": "Common", "price": 4},
    "j_burglar": {"key": "j_burglar", "name": "Burglar", "rarity": "Uncommon", "price": 6},
    "j_blackboard": {"key": "j_blackboard", "name": "Blackboard", "rarity": "Uncommon", "price": 6},
    "j_runner": {"key": "j_runner", "name": "Runner", "rarity": "Common", "price": 5},
    "j_ice_cream": {"key": "j_ice_cream", "name": "Ice Cream", "rarity": "Common", "price": 5},
    "j_dna": {"key": "j_dna", "name": "DNA", "rarity": "Rare", "price": 8},
    "j_splash": {"key": "j_splash", "name": "Splash", "rarity": "Common", "price": 3},
    "j_blue_joker": {"key": "j_blue_joker", "name": "Blue Joker", "rarity": "Common", "price": 5},
    "j_sixth_sense": {"key": "j_sixth_sense", "name": "Sixth Sense", "rarity": "Uncommon", "price": 6},
    "j_constellation": {"key": "j_constellation", "name": "Constellation", "rarity": "Uncommon", "price": 6},
    "j_hiker": {"key": "j_hiker", "name": "Hiker", "rarity": "Uncommon", "price": 5},
    "j_faceless": {"key": "j_faceless", "name": "Faceless Joker", "rarity": "Common", "price": 4},
    "j_green_joker": {"key": "j_green_joker", "name": "Green Joker", "rarity": "Common", "price": 4},
    "j_superposition": {"key": "j_superposition", "name": "Superposition", "rarity": "Common", "price": 4},
    "j_todo_list": {"key": "j_todo_list", "name": "To Do List", "rarity": "Common", "price": 4},
    "j_cavendish": {"key": "j_cavendish", "name": "Cavendish", "rarity": "Common", "price": 4},
    "j_card_sharp": {"key": "j_card_sharp", "name": "Card Sharp", "rarity": "Uncommon", "price": 6},
    "j_red_card": {"key": "j_red_card", "name": "Red Card", "rarity": "Common", "price": 5},
    "j_madness": {"key": "j_madness", "name": "Madness", "rarity": "Uncommon", "price": 7},
    "j_square": {"key": "j_square", "name": "Square Joker", "rarity": "Common", "price": 4},
    "j_seance": {"key": "j_seance", "name": "Seance", "rarity": "Uncommon", "price": 6},
    "j_riff_raff": {"key": "j_riff_raff", "name": "Riff-raff", "rarity": "Common", "price": 6},
    "j_vampire": {"key": "j_vampire", "name": "Vampire", "rarity": "Uncommon", "price": 7},
    "j_shortcut": {"key": "j_shortcut", "name": "Shortcut", "rarity": "Uncommon", "price": 7},
    "j_hologram": {"key": "j_hologram", "name": "Hologram", "rarity": "Uncommon", "price": 7},
    "j_vagabond": {"key": "j_vagabond", "name": "Vagabond", "rarity": "Rare", "price": 8},
    "j_baron": {"key": "j_baron", "name": "Baron", "rarity": "Rare", "price": 8},
    "j_cloud_9": {"key": "j_cloud_9", "name": "Cloud 9", "rarity": "Uncommon", "price": 7},
    "j_rocket": {"key": "j_rocket", "name": "Rocket", "rarity": "Uncommon", "price": 6},
    "j_obelisk": {"key": "j_obelisk", "name": "Obelisk", "rarity": "Rare", "price": 8},
    "j_midas_mask": {"key": "j_midas_mask", "name": "Midas Mask", "rarity": "Uncommon", "price": 7},
    "j_luchador": {"key": "j_luchador", "name": "Luchador", "rarity": "Uncommon", "price": 5},
    "j_photograph": {"key": "j_photograph", "name": "Photograph", "rarity": "Common", "price": 5},
    "j_gift": {"key": "j_gift", "name": "Gift Card", "rarity": "Uncommon", "price": 6},
    "j_turtle_bean": {"key": "j_turtle_bean", "name": "Turtle Bean", "rarity": "Uncommon", "price": 6},
    "j_erosion": {"key": "j_erosion", "name": "Erosion", "rarity": "Uncommon", "price": 6},
    "j_reserved_parking": {"key": "j_reserved_parking", "name": "Reserved Parking", "rarity": "Common", "price": 6},
    "j_mail": {"key": "j_mail", "name": "Mail-In Rebate", "rarity": "Common", "price": 4},
    "j_to_the_moon": {"key": "j_to_the_moon", "name": "To the Moon", "rarity": "Uncommon", "price": 5},
    "j_hallucination": {"key": "j_hallucination", "name": "Hallucination", "rarity": "Common", "price": 4},
    "j_fortune_teller": {"key": "j_fortune_teller", "name": "Fortune Teller", "rarity": "Common", "price": 6},
    "j_juggler": {"key": "j_juggler", "name": "Juggler", "rarity": "Common", "price": 4},
    "j_drunkard": {"key": "j_drunkard", "name": "Drunkard", "rarity": "Common", "price": 4},
    "j_stone": {"key": "j_stone", "name": "Stone Joker", "rarity": "Uncommon", "price": 6},
    "j_golden": {"key": "j_golden", "name": "Golden Joker", "rarity": "Common", "price": 6},
    "j_lucky_cat": {"key": "j_lucky_cat", "name": "Lucky Cat", "rarity": "Uncommon", "price": 6},
    "j_baseball": {"key": "j_baseball", "name": "Baseball Card", "rarity": "Rare", "price": 8},
    "j_bull": {"key": "j_bull", "name": "Bull", "rarity": "Uncommon", "price": 6},
    "j_diet_cola": {"key": "j_diet_cola", "name": "Diet Cola", "rarity": "Uncommon", "price": 6},
    "j_trading": {"key": "j_trading", "name": "Trading Card", "rarity": "Uncommon", "price": 6},
    "j_flash": {"key": "j_flash", "name": "Flash Card", "rarity": "Uncommon", "price": 5},
    "j_popcorn": {"key": "j_popcorn", "name": "Popcorn", "rarity": "Common", "price": 5},
    "j_trousers": {"key": "j_trousers", "name": "Spare Trousers", "rarity": "Uncommon", "price": 6},
    "j_ancient": {"key": "j_ancient", "name": "Ancient Joker", "rarity": "Rare", "price": 8},
    "j_ramen": {"key": "j_ramen", "name": "Ramen", "rarity": "Uncommon", "price": 6},
    "j_walkie_talkie": {"key": "j_walkie_talkie", "name": "Walkie Talkie", "rarity": "Common", "price": 4},
    "j_selzer": {"key": "j_selzer", "name": "Seltzer", "rarity": "Uncommon", "price": 6},
    "j_castle": {"key": "j_castle", "name": "Castle", "rarity": "Uncommon", "price": 6},
    "j_smiley": {"key": "j_smiley", "name": "Smiley Face", "rarity": "Common", "price": 4},
    "j_campfire": {"key": "j_campfire", "name": "Campfire", "rarity": "Rare", "price": 9},
    "j_ticket": {"key": "j_ticket", "name": "Golden Ticket", "rarity": "Common", "price": 5},
    "j_mr_bones": {"key": "j_mr_bones", "name": "Mr. Bones", "rarity": "Uncommon", "price": 5},
    "j_acrobat": {"key": "j_acrobat", "name": "Acrobat", "rarity": "Uncommon", "price": 6},
    "j_sock_and_buskin": {"key": "j_sock_and_buskin", "name": "Sock and Buskin", "rarity": "Uncommon", "price": 6},
    "j_swashbuckler": {"key": "j_swashbuckler", "name": "Swashbuckler", "rarity": "Common", "price": 4},
    "j_troubadour": {"key": "j_troubadour", "name": "Troubadour", "rarity": "Uncommon", "price": 6},
    "j_certificate": {"key": "j_certificate", "name": "Certificate", "rarity": "Uncommon", "price": 6},
    "j_smeared": {"key": "j_smeared", "name": "Smeared Joker", "rarity": "Uncommon", "price": 7},
    "j_throwback": {"key": "j_throwback", "name": "Throwback", "rarity": "Uncommon", "price": 6},
    "j_hanging_chad": {"key": "j_hanging_chad", "name": "Hanging Chad", "rarity": "Common", "price": 4},
    "j_rough_gem": {"key": "j_rough_gem", "name": "Rough Gem", "rarity": "Uncommon", "price": 7},
    "j_bloodstone": {"key": "j_bloodstone", "name": "Bloodstone", "rarity": "Uncommon", "price": 7},
    "j_arrowhead": {"key": "j_arrowhead", "name": "Arrowhead", "rarity": "Uncommon", "price": 7},
    "j_onyx_agate": {"key": "j_onyx_agate", "name": "Onyx Agate", "rarity": "Uncommon", "price": 7},
    "j_glass": {"key": "j_glass", "name": "Glass Joker", "rarity": "Uncommon", "price": 6},
    "j_ring_master": {"key": "j_ring_master", "name": "Showman", "rarity": "Uncommon", "price": 5},
    "j_flower_pot": {"key": "j_flower_pot", "name": "Flower Pot", "rarity": "Uncommon", "price": 6},
    "j_blueprint": {"key": "j_blueprint", "name": "Blueprint", "rarity": "Rare", "price": 10},
    "j_wee": {"key": "j_wee", "name": "Wee Joker", "rarity": "Rare", "price": 8},
    "j_merry_andy": {"key": "j_merry_andy", "name": "Merry Andy", "rarity": "Uncommon", "price": 7},
    "j_oops": {"key": "j_oops", "name": "Oops! All 6s", "rarity": "Uncommon", "price": 4},
    "j_idol": {"key": "j_idol", "name": "The Idol", "rarity": "Uncommon", "price": 6},
    "j_seeing_double": {"key": "j_seeing_double", "name": "Seeing Double", "rarity": "Uncommon", "price": 6},
    "j_matador": {"key": "j_matador", "name": "Matador", "rarity": "Uncommon", "price": 7},
    "j_hit_the_road": {"key": "j_hit_the_road", "name": "Hit the Road", "rarity": "Rare", "price": 8},
    "j_duo": {"key": "j_duo", "name": "The Duo", "rarity": "Rare", "price": 8},
    "j_trio": {"key": "j_trio", "name": "The Trio", "rarity": "Rare", "price": 8},
    "j_family": {"key": "j_family", "name": "The Family", "rarity": "Rare", "price": 8},
    "j_order": {"key": "j_order", "name": "The Order", "rarity": "Rare", "price": 8},
    "j_tribe": {"key": "j_tribe", "name": "The Tribe", "rarity": "Rare", "price": 8},
    "j_stuntman": {"key": "j_stuntman", "name": "Stuntman", "rarity": "Rare", "price": 7},
    "j_invisible": {"key": "j_invisible", "name": "Invisible Joker", "rarity": "Rare", "price": 8},
    "j_brainstorm": {"key": "j_brainstorm", "name": "Brainstorm", "rarity": "Rare", "price": 10},
    "j_satellite": {"key": "j_satellite", "name": "Satellite", "rarity": "Uncommon", "price": 6},
    "j_shoot_the_moon": {"key": "j_shoot_the_moon", "name": "Shoot the Moon", "rarity": "Common", "price": 5},
    "j_drivers_license": {"key": "j_drivers_license", "name": "Driver's License", "rarity": "Rare", "price": 7},
    "j_cartomancer": {"key": "j_cartomancer", "name": "Cartomancer", "rarity": "Uncommon", "price": 6},
    "j_astronomer": {"key": "j_astronomer", "name": "Astronomer", "rarity": "Uncommon", "price": 8},
    "j_burnt": {"key": "j_burnt", "name": "Burnt Joker", "rarity": "Rare", "price": 8},
    "j_bootstraps": {"key": "j_bootstraps", "name": "Bootstraps", "rarity": "Uncommon", "price": 7},
    "j_caino": {"key": "j_caino", "name": "Canio", "rarity": "Legendary", "price": 20},
    "j_triboulet": {"key": "j_triboulet", "name": "Triboulet", "rarity": "Legendary", "price": 20},
    "j_yorick": {"key": "j_yorick", "name": "Yorick", "rarity": "Legendary", "price": 20},
    "j_chicot": {"key": "j_chicot", "name": "Chicot", "rarity": "Legendary", "price": 20},
    "j_perkeo": {"key": "j_perkeo", "name": "Perkeo", "rarity": "Legendary", "price": 20},
}

# Legacy direct-call rarity weights (used only when random_joker_key(rng=None)).
# Real game: 70% common / 25% uncommon / 5% rare; legendaries never roll in
# shops — they only enter via The Soul spectral card.
RARITY_WEIGHTS = {"Common": 70, "Uncommon": 25, "Rare": 5}

# Real Balatro rarity thresholds (functions.hpp next_joker rarity poll):
# >0.95 rare, >0.7 uncommon, else common. Legendaries never roll in shops —
# they only enter via The Soul spectral card.
_RARITY_BY_POLL = {"3": "Rare", "2": "Uncommon", "1": "Common"}
# Legendary maps to rarity "4" → the real "Joker4" node (which has no
# source/ante suffix — see node_id.rs).
_JOKER_NODE_RARITY = {"Rare": "3", "Uncommon": "2", "Common": "1", "Legendary": "4"}

# Module-level joker ban list. Set by environments (e.g. MP env) to exclude
# specific jokers from shop generation. Standard Ranked multiplayer ruleset
# bans Chicot, Matador, Mr. Bones, Luchador (boss-blind interaction jokers).
BANNED_JOKERS: set[str] = set()


def set_banned_jokers(banned: set[str]):
    """Set the global banned joker list used by shop generation."""
    global BANNED_JOKERS
    BANNED_JOKERS = set(banned)


def clear_banned_jokers():
    """Clear the banned joker list (revert to base game)."""
    global BANNED_JOKERS
    BANNED_JOKERS = set()


# ────────────────────────────────────────────────────────────────────────────
# DUPLICATE SUPPRESSION (the Showman rule)
# ────────────────────────────────────────────────────────────────────────────
# Real game: without Showman, any Joker/Tarot/Planet/Spectral already in the
# player's possession is excluded from the pool for the rest of the run — in
# the Shop and Booster Packs alike. Merely *seeing* a card does not exclude it
# (it can reappear on a reroll). Showman lifts the rule for all four types.
#
# Draw mechanics mirror balatro-seed instance.rs::randchoice (a byte-accurate
# port of the real game): pick uniformly from the FULL pool; if the picked
# item is locked and Showman is not owned, re-draw from "{node_id}_resample{n}"
# nodes until an unlocked item appears (1000-resample fallback, after which a
# fully-owned pool re-allows duplicates). Draw counts match the real game's
# call structure, so seed-mode node pins stay aligned.

# Showman's real catalogue key (j_ring_master) and its legacy effect-registry
# key (j_showman); owning either lifts the no-duplicate rule.



def _showman_owned(game) -> bool:
    """True when the player owns Showman (its presence lifts duplicate
    suppression for Joker/Tarot/Planet/Spectral cards)."""
    return any(j.has_flag("allow_dupes") for j in getattr(game, "jokers", ()))


def _possessed_keys(game) -> set:
    """Keys the player currently possesses (joker slots + consumable area).

    Possession is the real game's lock source: selling a joker or using a
    consumable (with no copies remaining) re-allows it, so the locked set is
    computed live from game state rather than tracked separately."""
    keys = {j.key for j in getattr(game, "jokers", ())}
    keys.update(getattr(game, "consumable_hand", ()))
    return keys


def _locked_pool(game) -> set:
    """The key set a draw must avoid: everything possessed, or empty when
    Showman lifts the rule."""
    if _showman_owned(game):
        return set()
    return _possessed_keys(game)


def _draw_excluding(rng, node_id: str, pool, locked) -> object:
    """One pool draw with the real game's lock-triggered resample.

    Mirrors balatro-seed instance.rs::randchoice: pick uniformly from the FULL
    pool; if the picked item is locked (possessed, or temporarily locked while
    a pack is being generated), draw again from '{node_id}_resample{n}' nodes
    until an unlocked item appears (resample starts at 2; after 1000 resamples
    the last draw is returned even if locked — a fully-owned pool re-allows
    duplicates, exactly like the real game). `locked` empty → plain choice."""
    if not locked:
        return rng.node(node_id).choice(pool)
    item = rng.node(node_id).choice(pool)
    if item not in locked:
        return item
    resample = 2
    while True:
        item = rng.node(f"{node_id}_resample{resample}").choice(pool)
        resample += 1
        if item not in locked or resample > 1000:
            return item


def random_joker_key(
    rarity: Optional[str] = None,
    rng=None,
    ante: int = 1,
    source: str = "sho",
    game=None,
    exclude: Optional[set] = None,
) -> str:
    """Pick a random joker key, honoring BANNED_JOKERS.

    rng: an RngSource to draw through (per-node in seed mode), or None to use
    the module-level random (legacy direct-call behavior). When rng is given,
    the draw mirrors Balatro's node scheme: a rarity poll on
    "rarity{ante}{source}" then a pick from that rarity's pool on
    "Joker{1|2|3}{source}{ante}".

    game: when provided (and Showman is not owned), jokers already in the
    player's possession are excluded via the real lock-triggered resample.
    exclude: extra keys to treat as locked (e.g. jokers already drawn into the
    current pack, so a pack never repeats one); ignored when game is None or
    Showman is owned (the rule is fully lifted)."""
    if rng is None:
        if rarity:
            pool = [k for k, v in JOKER_CATALOGUE.items()
                    if v["rarity"] == rarity and k not in BANNED_JOKERS]
            return random.choice(pool) if pool else "j_joker"
        keys = [k for k in JOKER_CATALOGUE.keys() if k not in BANNED_JOKERS]
        weights = [RARITY_WEIGHTS.get(JOKER_CATALOGUE[k]["rarity"], 10) for k in keys]
        if not keys:
            return "j_joker"
        return random.choices(keys, weights=weights, k=1)[0]

    if rarity is None:
        poll = rng.node(node_rarity(source, ante)).random()
        rarity = _RARITY_BY_POLL["3" if poll > 0.95 else ("2" if poll > 0.7 else "1")]
    pool = [k for k, v in JOKER_CATALOGUE.items()
            if v["rarity"] == rarity and k not in BANNED_JOKERS]
    if not pool:
        return "j_joker"
    jnode = node_joker(_JOKER_NODE_RARITY[rarity], source, ante)
    if game is None or _showman_owned(game):
        # Showman lifts duplicate suppression entirely — even within-pack
        # `exclude` locks are bypassed (real game).
        return rng.node(jnode).choice(pool)
    locked = _possessed_keys(game)
    if exclude:
        locked = locked | set(exclude)
    return _draw_excluding(rng, jnode, pool, locked)


# ════════════════════════════════════════════════════════════════════════════
# SHOP ITEM
# ════════════════════════════════════════════════════════════════════════════

@dataclass
class ShopItem:
    kind: str          # "joker" | "planet" | "tarot" | "spectral" | "voucher" | "booster" | "card"
    key: str
    name: str
    price: int
    edition: str = "None"    # for jokers
    sold: bool = False
    card: Optional["Card"] = None   # Magic Trick: the offered playing card
    sell_bonus: int = 0      # Gift Card: +$1 sell value on shop cards (per round)

    def discounted_price(self, discount_frac: float) -> int:
        return max(1, int(self.price * (1 - discount_frac)))


# ════════════════════════════════════════════════════════════════════════════
# SHOP GENERATION
# ════════════════════════════════════════════════════════════════════════════

BOOSTER_CATALOGUE = {
    "p_arcana":        ("Arcana Pack",     4, "tarot",    3),   # 3 tarots, pick 1
    "p_arcana_jumbo":  ("Jumbo Arcana",    6, "tarot",    5),
    "p_arcana_mega":   ("Mega Arcana",     8, "tarot",    5),   # pick 2
    "p_celestial":     ("Celestial Pack",  4, "planet",   3),
    "p_celestial_jumbo":("Jumbo Celestial",6, "planet",   5),
    "p_celestial_mega":("Mega Celestial",  8, "planet",   5),
    "p_spectral":      ("Spectral Pack",   4, "spectral", 2),
    "p_spectral_jumbo":("Jumbo Spectral",  6, "spectral", 4),
    "p_spectral_mega": ("Mega Spectral",   8, "spectral", 4),
    "p_standard":      ("Standard Pack",   4, "card",     3),
    "p_standard_jumbo":("Jumbo Standard",  6, "card",     5),
    "p_buffoon":       ("Buffoon Pack",    4, "joker",    2),
    "p_buffoon_jumbo": ("Jumbo Buffoon",   6, "joker",    4),
    # All Mega packs cost $8; Mega Buffoon holds 4 jokers (choose 2) — the
    # real 2/4/4 (Normal/Jumbo/Mega) Buffoon progression (§15). The Buffoon /
    # Standard Tags grant the Mega packs for free, but they are also
    # shop-legal in the real game (see PACK_WEIGHTS below).
    "p_buffoon_mega":  ("Mega Buffoon",    8, "joker",    4),
    "p_standard_mega": ("Mega Standard",   8, "card",     5),
}

# Real Booster-Pack type/size rates (wiki Booster Packs page; balatro-seed
# pools.rs PACKS — the 15 entries sum to 22.42, the table's RETRY sentinel).
# Every size of every type is shop-legal in the real game, incl. the Mega
# Buffoon/Standard (weights 0.15 / 0.5). Pool order matches balatro-seed's
# PACKS layout (Arcana, Celestial, Standard, Buffoon, Spectral × Normal /
# Jumbo / Mega) so the weighted draw stays byte-aligned with the real game.
PACK_WEIGHTS: dict[str, float] = {
    "p_arcana": 4.0, "p_arcana_jumbo": 2.0, "p_arcana_mega": 0.5,
    "p_celestial": 4.0, "p_celestial_jumbo": 2.0, "p_celestial_mega": 0.5,
    "p_standard": 4.0, "p_standard_jumbo": 2.0, "p_standard_mega": 0.5,
    "p_buffoon": 1.2, "p_buffoon_jumbo": 0.6, "p_buffoon_mega": 0.15,
    "p_spectral": 0.6, "p_spectral_jumbo": 0.3, "p_spectral_mega": 0.07,
}
SHOP_PACK_POOL = list(PACK_WEIGHTS)
SHOP_PACK_WEIGHTS = [PACK_WEIGHTS[k] for k in SHOP_PACK_POOL]

def generate_shop(game: "BalatroGame", restock_voucher: bool = False) -> list[ShopItem]:
    """Generate a full shop for the current ante/round.

    Consumes one-shot skip-blind Tag shop modifiers (Coupon / D6 / Uncommon /
    Rare / Foil-Holo-Poly-Negative / Voucher Tags) — they apply to the first
    shop generated after the skipped blind.

    restock_voucher: roll a fresh voucher for the shop slot. The real game's
    Voucher persists across non-Boss blinds and rerolls — it restocks only
    after the Boss Blind is defeated (or the run's first shop, when no voucher
    has been offered yet). Buying the offered voucher empties the slot until
    the next restock.
    """
    items: list[ShopItem] = []

    # Gift Card (j_gift): "Adds $1 to the sell value of every Joker and
    # Consumable card in the shop at the end of the round" — the round-end
    # on_round_end hook parks pending_shop_buff; consume it here and add +$1
    # sell value to this shop's jokers (consumable sell values are not modeled).
    shop_buff = any(j.state.pop("pending_shop_buff", False) for j in game.jokers)

    # Consume pending tag modifiers (one-shot, apply to THIS shop only)
    coupon = game.pending_coupon
    game.pending_coupon = False
    free_rarity = game.pending_free_rarity
    game.pending_free_rarity = None
    free_edition = game.pending_free_edition
    game.pending_free_edition = None
    voucher_extra = game.pending_voucher
    game.pending_voucher = False
    if game.pending_reroll_free:
        game.pending_reroll_free = False
        game.reroll_cost = 0   # D6 Tag: rerolls in the next shop start at $0

    # Hone / Glow Up: 2x / 4x edition odds (Polychrome's effective 3x / 7x
    # comes out of the poll thresholds — see _roll_edition). Applied to shop
    # jokers AND Buffoon-pack jokers alike (real game: next_joker reads
    # G.GAME.edition_rate for every joker regardless of source).
    edition_boost = _edition_boost(game)

    # cdt-polled random slots (real game: G.GAME.shop.joker_max — 2 base, +1
    # per Overstock/Overstock Plus). Each slot independently rolls the cdt{ante}
    # item-type poll (Joker 20 / Tarot 4 / Planet 4), so a slot can be a Tarot
    # or Planet rather than always a Joker.
    for i in range(game.shop_item_slots):
        if i == 0 and free_rarity:
            # Uncommon/Rare Tag: the first slot is a free Joker of that rarity
            key = random_joker_key(rarity=free_rarity, rng=game.rng,
                                   ante=game.ante, source="sho", game=game)
            info = JOKER_CATALOGUE.get(key, {})
            items.append(ShopItem("joker", key, info.get("name", key), 0,
                                  sell_bonus=1 if shop_buff else 0))
        elif i == 0 and free_edition:
            # Foil/Holographic/Polychrome/Negative Tag: free Joker with the edition
            key = random_joker_key(rng=game.rng, ante=game.ante, source="sho", game=game)
            info = JOKER_CATALOGUE.get(key, {})
            items.append(ShopItem("joker", key, info.get("name", key), 0, free_edition,
                                  sell_bonus=1 if shop_buff else 0))
        else:
            item = _random_shop_item(game, edition_boost)
            if item.kind in ("joker", "tarot", "planet", "spectral") and shop_buff:
                item.sell_bonus = 1
            items.append(item)

    # Voucher slot (1; +1 with the Voucher Tag). Real game (§17 + wiki): the
    # Voucher offered in the shop persists across non-Boss blinds and rerolls
    # (the same card stays until bought); it restocks only after the Boss Blind
    # is defeated. `restock_voucher` (boss beaten) or `offered_voucher is None`
    # (run's first shop) triggers a fresh roll; the Voucher Tag's extra slot is
    # always a fresh draw.
    # offered_voucher states: None = nothing offered yet (roll on first shop),
    # key = currently on offer, "" = pool exhausted / slot intentionally empty
    # (bought, or all 32 vouchers owned) — "" keeps non-Boss shops draw-free.
    if restock_voucher or game.offered_voucher is None:
        game.offered_voucher = _random_voucher(game) or ""
    if game.offered_voucher and game.offered_voucher not in game.vouchers:
        items.append(ShopItem(
            "voucher", game.offered_voucher,
            VOUCHER_NAME.get(game.offered_voucher, game.offered_voucher), 10
        ))
    if voucher_extra:
        extra = _random_voucher(
            game,
            exclude={game.offered_voucher} if game.offered_voucher else None,
        )
        if extra and extra not in game.vouchers:
            items.append(ShopItem(
                "voucher", extra,
                VOUCHER_NAME.get(extra, extra), 10
            ))

    # Booster pack slots (2). The first pack of a run is always a normal
    # Buffoon Pack (real game: G.GAME.first_shop_buffoon in get_pack); it
    # consumes no seeded pack-generic draw (the real game uses unseeded
    # math.random for the variant), so the second slot gets draw #1. Pack
    # type/size is a weighted draw on shop_pack{ante} using the real rates
    # (PACK_WEIGHTS — balatro-seed's randweightedchoice on pools::PACKS).
    for i in range(2):
        if i == 0 and not game.first_shop_buffoon:
            game.first_shop_buffoon = True
            bkey = "p_buffoon"
        else:
            bkey = game.rng.node(node_shop_pack(game.ante)).choices(
                SHOP_PACK_POOL, SHOP_PACK_WEIGHTS)[0]
        bname, bprice, _, _ = BOOSTER_CATALOGUE[bkey]
        items.append(ShopItem("booster", bkey, bname, bprice))

    # Coupon Tag: initial cards and booster packs in the next shop are free
    # (vouchers excluded, matching the real effect)
    if coupon:
        for item in items:
            if item.kind != "voucher":
                item.price = 0

    return items


def _shop_item_weights(game: "BalatroGame") -> tuple[list[str], list[float]]:
    """Real cdt{ante} shop item-type poll (game's create_card_for_shop /
    functions.hpp nextShopItem): Joker 20 / Tarot 4 / Planet 4. Tarot/Planet
    Merchant → 9.6, Tycoon → 32 (real game: rate = 4 * extra). Magic Trick /
    Illusion add a playing-card kind at weight 4. Spectrals (weight 2) appear
    only with Ghost Deck — not in the Red-Deck spec lock."""
    v = game.vouchers
    w_tarot = (32.0 if "v_tarot_tycoon" in v
               else 9.6 if "v_tarot_merchant" in v else 4.0)
    w_planet = (32.0 if "v_planet_tycoon" in v
                else 9.6 if "v_planet_merchant" in v else 4.0)
    pool = ["joker", "tarot", "planet"]
    weights = [20.0, w_tarot, w_planet]
    if "v_magic_trick" in v or "v_illusion" in v:
        pool.append("card")
        weights.append(4.0)
    return pool, weights


def _random_shop_item(game: "BalatroGame", edition_boost: float = 1.0) -> ShopItem:
    """Generate one cdt-polled shop slot: poll the item type, then build the
    matching item (Joker with rarity + edition roll, Tarot, Planet, or a
    Magic Trick playing card). Mirrors the real game's create_card_for_shop."""
    pool, weights = _shop_item_weights(game)
    kind = game.rng.node(node_cdt(game.ante)).choices(pool, weights)[0]
    ante = game.ante
    if kind == "joker":
        key = random_joker_key(rng=game.rng, ante=ante, source="sho", game=game)
        info = JOKER_CATALOGUE.get(key, {})
        edition = _roll_edition(
            game.rng.node(node_edition("sho", ante)), edition_boost)
        price = info.get("price", 6)
        if edition != "None":
            price += _edition_markup(edition)
        return ShopItem("joker", key, info.get("name", key), price, edition)
    if kind == "tarot":
        key = _draw_excluding(game.rng, node_tarot("sho", ante), ALL_TAROTS,
                              _locked_pool(game))
        return ShopItem("tarot", key, TAROT_NAME.get(key, key), 3)
    if kind == "planet":
        key = _draw_excluding(game.rng, node_planet("sho", ante), ALL_PLANETS,
                              _locked_pool(game))
        # Astronomer (j_astronomer): "All Planet cards in the shop cost $0"
        price = 0 if any(j.has_flag("free_planets") for j in game.jokers) else 3
        return ShopItem("planet", key, PLANET_NAME.get(key, key), price)
    return _shop_card_item(game)


def _shop_card_item(game: "BalatroGame") -> ShopItem:
    """A playing-card shop item ($1, Magic Trick). Illusion adds an
    enhancement (40%) and/or edition (20% — Foil/Holographic/Polychrome only,
    never Negative; seals are bugged off in the real game)."""
    from .card import Card
    from .constants import RANK_NAMES, SUITS

    node = game.rng.node(MAGIC_CARD_NODE)
    rank = node.randint(2, 14)
    suit = node.choice(SUITS)
    enhancement = edition = "None"
    if "v_illusion" in game.vouchers:
        inode = game.rng.node(ILLUSION_NODE)
        # Real game (UI_definitions.lua create_card_for_shop): Enhancement 40%
        # (pseudorandom('illusion') > 0.6), Edition 20% (pseudorandom > 0.8).
        # Edition split matches the real poll: Foil 50% / Holographic 35% /
        # Polychrome 15%. Negative never appears on playing cards.
        if inode.chance(0.4):
            enhancement = inode.choice([e for e in ENHANCEMENTS if e != "None"])
        if inode.chance(0.2):
            r = inode.random()
            if r > 0.85:
                edition = "Polychrome"
            elif r > 0.5:
                edition = "Holographic"
            else:
                edition = "Foil"
    card = Card(rank, suit, enhancement=enhancement, edition=edition)
    name = f"{RANK_NAMES[rank]} of {suit}"
    return ShopItem("card", f"card_{rank}_{suit}", name, 1, card=card)


def _random_voucher(game: "BalatroGame",
                    exclude: Optional[set] = None) -> Optional[str]:
    """Pick a voucher for the shop slot. Upgraded vouchers only appear once
    their base pair is owned (real-game pair-unlock rule).

    exclude: extra keys to skip (the Voucher Tag's extra slot must not offer
    the same voucher as the persistent slot)."""
    available = []
    for v in ALL_VOUCHERS:
        if v in game.vouchers:
            continue
        if exclude and v in exclude:
            continue
        base = VOUCHER_BASE.get(v)
        if base is not None and base not in game.vouchers:
            continue
        available.append(v)
    if not available:
        # Real game falls back to offering Blank repeatedly once every voucher
        # is purchased; the sim just leaves the voucher slot empty.
        return None
    return game.rng.node(node_voucher(game.ante)).choice(available)


def _edition_boost(game: "BalatroGame") -> int:
    """Hone / Glow Up edition-rate multiplier (2x / 4x). Polychrome's effective
    3x / 7x boost falls out of the poll thresholds (see _roll_edition)."""
    if "v_glow_up" in game.vouchers:
        return 4
    if "v_hone" in game.vouchers:
        return 2
    return 1


def _roll_edition(node=None, boost: float = 1.0) -> str:
    """Edition roll; thresholds match real Balatro (next_joker's edition poll).
    node: a NodeRng to draw through (per-node in seed mode); None → module
    random (legacy direct-call behavior).
    boost: Hone (2) / Glow Up (4) multiply Foil + Holographic appearance;
    Polychrome gets 3x for Hone / 7x for Glow Up (the real game's quirk)."""
    r = node.random() if node is not None else random.random()
    if boost <= 1.0:
        if r < 0.003:   return "Negative"
        if r < 0.006:   return "Polychrome"
        if r < 0.02:    return "Holographic"
        if r < 0.04:    return "Foil"
        return "None"
    poly_boost = 7.0 if boost >= 4.0 else 3.0
    t_poly = 0.003 + 0.003 * poly_boost
    t_holo = t_poly + 0.014 * boost
    t_foil = t_holo + 0.02 * boost
    if r < 0.003:   return "Negative"
    if r < t_poly:  return "Polychrome"
    if r < t_holo:  return "Holographic"
    if r < t_foil:  return "Foil"
    return "None"


def _edition_markup(edition: str) -> int:
    return {"Foil": 2, "Holographic": 3, "Polychrome": 5, "Negative": 5}.get(edition, 0)


# ════════════════════════════════════════════════════════════════════════════
# BUY / SELL LOGIC
# ════════════════════════════════════════════════════════════════════════════

def buy_item(game: "BalatroGame", item: ShopItem) -> bool:
    """
    Attempt to purchase a shop item. Returns True on success.
    Modifies game.dollars, game.jokers, game.consumable_hand as appropriate.
    """
    if item.sold:
        return False

    effective_price = item.discounted_price(game.shop_discount)
    # Credit Card: "Go up to -$20 in debt" — purchases are allowed even when
    # unaffordable, down to a -$20 balance (capability flag, R3).
    credit = any(j.has_flag("debt") for j in game.jokers)
    if game.dollars - effective_price < (-20 if credit else 0):
        return False

    if item.kind == "joker":
        if len(game.jokers) >= game.joker_slots and item.edition != "Negative":
            return False
        j = game.grant_joker(item.key, item.edition)
        if j is None:
            return False
        j.state["sell_value"] = max(1, effective_price // 2) + item.sell_bonus
        game.dollars -= effective_price
        game.run_stats["money_spent"] += effective_price
        game.run_stats["jokers_bought"].append(item.key)
        item.sold = True
        return True

    if item.kind in ("planet", "tarot", "spectral"):
        if len(game.consumable_hand) >= game.consumable_slots:
            return False
        game.consumable_hand.append(item.key)
        game.dollars -= effective_price
        game.run_stats["money_spent"] += effective_price
        game.run_stats["consumables_bought"] += 1
        item.sold = True
        return True

    if item.kind == "voucher":
        from .consumables import apply_voucher
        if apply_voucher(game, item.key):
            game.dollars -= effective_price
            game.run_stats["money_spent"] += effective_price
            game.run_stats["vouchers_bought"] += 1
            item.sold = True
            return True
        return False

    if item.kind == "card":
        # Magic Trick: buying a playing card adds it to the run deck
        if item.card is None:
            return False
        game.deck.insert(0, item.card)
        # Hologram: X0.25 per card added to the run (M1 B2 on_card_added)
        for j in game.jokers:
            j.fire("on_card_added", None)
        game.dollars -= effective_price
        game.run_stats["money_spent"] += effective_price
        game.run_stats["cards_bought"] += 1
        item.sold = True
        return True

    if item.kind == "booster":
        game.dollars -= effective_price
        game.run_stats["money_spent"] += effective_price
        game.run_stats["packs_bought"] += 1
        item.sold = True
        _open_booster(game, item.key)
        from .game import State
        game.state = State.BOOSTER_OPEN   # agent picks from the pack next
        return True

    return False


def sell_joker(game: "BalatroGame", joker_idx: int) -> int:
    """Sell joker at index. Returns dollars gained (0 if invalid)."""
    if joker_idx < 0 or joker_idx >= len(game.jokers):
        return 0
    j = game.jokers.pop(joker_idx)
    sell_value = j.state.get("sell_value", 2)
    game.dollars += sell_value
    # Synergy-tree telemetry (observation-only): (ante, key) on sale — pairs
    # with run_stats["jokers_bought"] / co_owned to reconstruct loadouts.
    game.run_stats["jokers_sold"].append((game.ante, j.key))
    # Fire on_sell hooks on the sold joker itself (Luchador, Invisible Joker,
    # Diet Cola — they need the sold instance's own state)
    j.fire("on_sell", None)
    # Fire on_other_sold on every REMAINING joker: Campfire grows on ANY card
    # sold (real game). Dedicated hook so unrelated on_sell effects never fire
    # for someone else's sale.
    for other in game.jokers:
        other.fire("on_other_sold", None)
    return sell_value


def reroll_shop(game: "BalatroGame") -> bool:
    """Pay for a reroll. Returns True on success.

    Real game: rerolling replaces the Jokers/Tarots/Planets but does NOT
    restock Booster Packs or the Voucher (reference §17) — those persist until
    the next shop entry / next Boss Blind respectively.
    """
    cost = max(0, game.reroll_cost - game.reroll_discount)
    # Chaos the Clown (j_chaos): "First reroll in the shop is free" — its
    # on_shop_enter parks free_reroll on the joker; consume it here.
    for j in game.jokers:
        if j.state.pop("free_reroll", False):
            cost = 0
            break
    if game.free_rerolls_remaining > 0:
        game.free_rerolls_remaining -= 1
        cost = 0
    if game.dollars < cost:
        return False
    game.dollars -= cost
    game.run_stats["money_spent"] += cost
    game.run_stats["rerolls"] += 1
    game.reroll_cost += 1
    # Flash Card (j_flash): +2 Mult permanently per shop reroll used (M1 B2
    # on_reroll hook dispatch). Fires whether or not the reroll is free.
    for j in game.jokers:
        j.fire("on_reroll", None)
    # Keep the currently-offered voucher (restock_voucher=False): rerolls never
    # restock the Voucher slot.
    game.current_shop = generate_shop(game, restock_voucher=False)
    return True


# ════════════════════════════════════════════════════════════════════════════
# BOOSTER PACK OPENING
# ════════════════════════════════════════════════════════════════════════════

# Real Standard-Pack pools (balatro-seed pools.rs, order-matched so the
# frontsta{ante} draw stays byte-aligned with the real game): the 8 real
# enhancements (constants.ENHANCEMENTS sans "None" — same order as the real
# pool), and the 52-card base pool in the real CARDS ordering — suit blocks
# Clubs/Diamonds/Hearts/Spades; ranks 2-9, A, J, K, Q, T. Sim rank ints:
# A=14, J=11, K=13, Q=12, T=10.
_STD_ENHANCEMENTS = [e for e in ENHANCEMENTS if e != "None"]
_STD_CARD_POOL = [
    (rank, suit)
    for suit in ("Clubs", "Diamonds", "Hearts", "Spades")
    for rank in (2, 3, 4, 5, 6, 7, 8, 9, 14, 11, 13, 12, 10)
]


def _roll_standard_card(game: "BalatroGame") -> "Card":
    """Generate one Standard-Pack playing card with the real modifier odds.

    Mirrors the real game's nextStandardCard roll sequence (balatro-seed
    draws.rs::next_standard_card), per card:
      1. enhancement poll (stdset{ante}): > 0.6 → 40% enhanced, type drawn
         from the 8 real enhancements (Enhancedsta{ante});
      2. base card (frontsta{ante}) — one draw from the 52-card pool, so
         duplicates within a pack are expected (real behavior);
      3. edition poll (standard_edition{ante}): Foil 4% / Holographic 2.8% /
         Polychrome 1.2% — NOT boosted by Hone/Glow Up (only next_joker
         reads G.GAME.edition_rate);
      4. seal poll (stdseal{ante}): > 0.8 → 20% sealed, type evenly split
         across the 4 variants (stdsealtype{ante}).
    """
    from .card import Card

    enhancement = "None"
    if game.rng.node(node_stdset(game.ante)).random() > 0.6:   # 40%
        enhancement = game.rng.node(
            node_std_enhanced(game.ante)).choice(_STD_ENHANCEMENTS)

    rank, suit = game.rng.node(node_std_front(game.ante)).choice(_STD_CARD_POOL)

    r = game.rng.node(node_std_edition(game.ante)).random()
    edition = ("Polychrome" if r > 0.988 else
               "Holographic" if r > 0.96 else
               "Foil" if r > 0.92 else "None")

    seal = "None"
    if game.rng.node(node_std_seal(game.ante)).random() > 0.8:   # 20%
        sr = game.rng.node(node_std_seal_type(game.ante)).random()
        seal = ("Red" if sr > 0.75 else
                "Blue" if sr > 0.5 else
                "Gold" if sr > 0.25 else "Purple")

    return Card(rank, suit, enhancement=enhancement, edition=edition,
                seal=seal)


def _open_booster(game: "BalatroGame", booster_key: str):
    """Open a booster pack — add options to game.booster_choices for the agent to pick."""
    info = BOOSTER_CATALOGUE.get(booster_key)
    if not info:
        return
    _, _, content_kind, n_cards = info
    # Hallucination (j_hallucination): 1-in-2 chance of a Tarot when any
    # Booster Pack is opened (M1 B2 on_booster_opened dispatch). The hook
    # parks the reward on its own state (no ScoreContext exists here); collect
    # and grant it to the consumable area.
    for j in game.jokers:
        j.fire("on_booster_opened", None)
        game._grant_pending(j.state.pop("pending_consumables", []))
    picks = 2 if "mega" in booster_key else 1
    # Hone / Glow Up boost Buffoon-pack joker editions identically to shop
    # jokers (real game: next_joker reads G.GAME.edition_rate regardless of
    # source — see _edition_boost).
    edition_boost = _edition_boost(game)

    # Pack contents honor the same duplicate-suppression rule as the shop:
    # cards the player possesses are excluded (unless Showman is owned), and
    # each card drawn into this pack is temporarily locked so a pack never
    # repeats one — the real game locks each drawn card until the pack is fully
    # generated (balatro-seed draws.rs::next_*_pack). Standard packs are exempt
    # (playing-card duplicates are expected, matching the real game).
    showman = _showman_owned(game)
    locked = _locked_pool(game)   # possession locks; empty when Showman is owned
    inpack = set()                # cards drawn into this pack — also bypassed by Showman
    choices = []
    if content_kind == "tarot":
        # Omen Globe: 20% chance each Arcana-Pack Tarot is replaced by a
        # Spectral card (real-game effect).
        omen = "v_omen_globe" in game.vouchers
        omen_node = game.rng.node(OMEN_NODE)
        for _ in range(n_cards):
            excl = locked if showman else (locked | inpack)
            key = _draw_excluding(game.rng, node_tarot("ar1", game.ante),
                                  ALL_TAROTS, excl)
            if omen and omen_node.chance(0.2):
                key = _draw_excluding(game.rng, node_spectral("spe", game.ante),
                                      ALL_SPECTRALS, excl)
            choices.append(key)
            inpack.add(key)
    elif content_kind == "planet":
        # Telescope: Celestial Packs always contain the Planet card for the
        # most-played hand (tie-break: the higher-tier hand, real-game rule).
        forced = None
        if "v_telescope" in game.vouchers:
            counts = getattr(game, "run_hand_counts", None)
            if counts:
                most = max(counts, key=lambda h: (counts[h], _HAND_TIERS.get(h, 0)))
                forced = {v: k for k, v in PLANET_HAND.items()}.get(most)
        for i in range(n_cards):
            if forced is not None and i == 0:
                choices.append(forced)
                inpack.add(forced)
                continue
            key = _draw_excluding(game.rng, node_planet("pl1", game.ante),
                                  ALL_PLANETS, locked if showman else (locked | inpack))
            choices.append(key)
            inpack.add(key)
    elif content_kind == "spectral":
        for _ in range(n_cards):
            key = _draw_excluding(game.rng, node_spectral("spe", game.ante),
                                  ALL_SPECTRALS, locked if showman else (locked | inpack))
            choices.append(key)
            inpack.add(key)
    elif content_kind == "joker":
        # Real game (functions.hpp next_joker, mirrored by balatro-seed):
        # Buffoon-pack jokers roll the SAME edition poll as shop jokers, on
        # the edibuf{ante} node, with Hone/Glow Up boosting it identically.
        # Choices carry the edition as ("joker", key, edition) tuples.
        ednode = game.rng.node(node_edition("buf", game.ante))
        for _ in range(n_cards):
            key = random_joker_key(rng=game.rng, ante=game.ante,
                                   source="buf", game=game,
                                   exclude={c[1] for c in choices})
            choices.append(("joker", key, _roll_edition(ednode, edition_boost)))
    elif content_kind == "card":
        # Real game (functions.hpp::nextStandardCard, mirrored by balatro-seed
        # draws.rs::next_standard_card): each Standard-Pack card rolls an
        # enhancement (40%), a base card, an edition (Foil 4% / Holographic
        # 2.8% / Polychrome 1.2%) and a seal (20%). Unlike every other pack,
        # drawn cards are never locked — duplicates within one Standard Pack
        # are expected. Choices stay the ("card", card) tuple convention.
        choices = [("card", _roll_standard_card(game)) for _ in range(n_cards)]

    game.booster_choices = choices
    game.booster_picks_remaining = picks



