"""
jokers/ — Joker effect implementations.

Each effect subclasses JokerEffect (base.py) and is registered by canonical
key via the @register_joker("j_x") decorator; JOKER_REGISTRY maps key ->
singleton effect object. Effects declare hooks (no-ops on the base, so engine
dispatch is a plain per-instance fire), capability flags
(`flags = frozenset({...})`), blind-start passives (`passives()`), and
per-effect `state_defaults`.

Hooks:
  pre_score(ctx)                    — before the card loop (retriggers, flags)
  on_score_card(card, ctx)          — once per scoring card
  on_hand_scored(ctx)               — after all cards score
  on_discard(cards, ctx)            — on discard
  on_round_end(ctx)                 — round cash-out
  on_blind_selected(ctx)            — blind selected (reward creation)
  on_blind_skipped(ctx)             — blind skipped
  on_boss_beaten(ctx)               — boss blind defeated
  on_boss_ability_triggered(ctx)    — Matador payout
  on_planet_used(planet)            — planet card used
  on_tarot_used(ctx)                — tarot card used
  on_lucky_trigger(ctx)             — Lucky card triggered
  on_reroll(ctx) / on_booster_opened(ctx) / on_booster_skipped(ctx)
  on_sell(ctx) / on_other_sold(ctx) / on_shop_enter(ctx) / on_shop_leave(ctx)
  on_card_added(ctx) / on_card_destroyed(card, ctx)

Canonical-key aliases (real game ids -> sim effect classes) are applied at
the bottom of this module; per-module import order is only organizational.
"""
from .base import JOKER_REGISTRY, JokerInstance, register_joker

# Import order is only organizational — keys are registered disjointly via
# decorators, and canonical aliases are applied below.
from . import economy     # noqa: F401  — money jokers
from . import scaling     # noqa: F401  — persistent state jokers
from . import hand_type   # noqa: F401  — hand-type conditional jokers
from . import misc        # noqa: F401  — retrigger, blueprint, special mechanics
from . import chips       # noqa: F401  — flat bonus jokers
from . import mult        # noqa: F401  — mult/xMult jokers (canonical, loads last)


# ── Canonical-key aliases: real-game joker ids → sim effect classes ────

# The shop sells under the real game's ids (balatro-rs joker_data!). Legacy
# sim keys are aliased so a canonical id resolves to the same effect class;
# applied LAST so aliases win over any earlier registration (e.g. j_ring_master
# -> Showman, j_ticket -> Golden Ticket).
# Generated by tools/gen_joker_catalogue.py.
_CANONICAL_JOKER_ALIASES = {
    "j_burnt": "j_burnt_joker",
    "j_business": "j_business_card",
    "j_gift": "j_gift_card",
    "j_glass": "j_glass_joker",
    "j_idol": "j_the_idol",
    "j_invisible": "j_invisible_joker",
    "j_gluttenous_joker": "j_gluttonous_joker",  # real id misspells it; native key corrects
    "j_mail": "j_mail_in_rebate",
    "j_ring_master": "j_showman",
    "j_selzer": "j_seltzer",
    "j_smeared": "j_smeared_joker",
    "j_space": "j_space_joker",
    "j_square": "j_square_joker",
    "j_stone": "j_stone_joker",
    "j_ticket": "j_golden_ticket",
    "j_todo_list": "j_to_do_list",
    "j_trading": "j_trading_card",
    "j_trousers": "j_spare_trousers",
}

for _canon, _legacy in _CANONICAL_JOKER_ALIASES.items():
    if _legacy in JOKER_REGISTRY:
        JOKER_REGISTRY[_canon] = JOKER_REGISTRY[_legacy]
